### ISSUE TITLE
Easier solution using a component

### ISSUE THREAD

**Issue by OrchardSkills** [kinetiq/Blazor.WithMVC#1]
Hey Brian. 

If you use a component you can just integrate the counter directly into the MCV Web Application. For me, it was much easier. So, in Index.cshtml just call:

```
<component type="typeof(Demo.Web.Components.Counter)" param-InitialValue="0" render-mode="Server" /> 
```

You will need to create a _Imports.razor

```
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.JSInterop
@using Demo.Web.BlazorComponentsMVCWebApp
@using Demo.Web.BlazorComponentsMVCWebApp.Components
@using Demo.Web.BlazorComponentsMVCWebApp.Controllers
@using Demo.Web.BlazorComponentsMVCWebApp.Models
```
Create a Components folder
Create a Components/Counter.razor file:

```
<h3>Counter</h3>
<p>Current count: @currentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    [Parameter]
    public int InitialValue { get; set; }

    private void IncrementCount() => currentCount++;

    protected override void OnParametersSet()
    {
        currentCount = InitialValue;
    }
}
```

Modify Views/Home/Index.cshtml

```
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <!--
    There are 3 available render modes:
    Static:            Renders the component into static HTML. In this case, there is no interactivity and you can remove the blazor.server.js script.
    Server:            Renders a marker for a Blazor server-side application. This doesn't include any output from the component.
                       When the user-agent starts, it uses this marker to bootstrap a blazor application. 
                       This means until the SignalR connection is set up, there is nothing visible for the user.
    ServerPrerendered: Renders the component into static HTML and includes a marker for a Blazor server-side application. When the user-agent starts,
                       it uses this marker to bootstrap a blazor application. This means until the SignalR connection is set up,
                       the user can see the content of the component but cannot interact with it.
    -->
    <component type="typeof(Demo.Web.Components.Counter)" param-InitialValue="0" render-mode="Server" />
</div>

@section Scripts {
    <script src="_framework/blazor.server.js"></script>
}
```

You can look at my example: https://github.com/OrchardSkills/OrchardSkills.BlazorComponentsMVCWebApp Thank You.

**Comment by kinetiq** [comment]
Thanks for this. You make a good point that it is possible to embed Blazor components directly into any MVC page, bypassing a lot of the standard Blazor infrastructure.

There are scenarios where this may be appropriate. For instance, I found that in order for my Blazor-based pages to look like the rest of my site, I had to make a Blazor version of the menu which is fairly involved in my case (role-based menu items, a search box with autocomplete, etc). I've been thinking it might make sense to actually replace the MVC version of the menu with the new Blazor component so that I only have to maintain one version of it. That should work because it is self-contained.

But that's where I will likely stop. In general, I prefer not to mix Blazor and MVC. In particular, I feel that adding Blazor components to existing MVC pages can result in extra complexity unless you are very careful. I suspect the pattern will coalesce around either re-working the whole controller in Blazor or sticking with MVC. 

My intention here is to show people how to use a fairly vanilla Blazor setup side-by-side with MVC in the same project, in a way that can scale and is compatible with most of the help available online.
